### PR TITLE
[Docs] Add module installation instructions

### PR DESCRIPTION
**Pull request by Naktibalda**

### CODE REVIEW

**Comment by Naktibalda** [comment]
1. The code for generating instructions is at https://github.com/Codeception/util-robohelpers/pull/1/files

**Comment by Naktibalda** [comment]
Dynamically generating `(if you use Phar distribution, the module is already installed) is a bit difficult.

**Comment by Naktibalda** [comment]
How about these?

## Installation

If you use Codeception installed using composer, install this module with the following command:

```
composer require --dev codeception/AMQP
```

Alternatively, you can enable `AMQP` module in suite configuration file and run
 
```
codecept init upgrade4`.
```

This module was bundled with Codeception 2 and 3, but since version 4 it is necessary to install it separately. 
Some modules are bundled with PHAR files.
Warning. Using PHAR file and composer in the same project can cause unexpected errors.

**Comment by DavertMik** [comment]
Seems fine!

**Comment by Naktibalda** [comment]
@DavertMik Is there a way to make warning more prominent?

**Comment by DavertMik** [comment]
Not sure, but overall looks fine

**Pull request merged**
