### PR TITLE
Mentioning core features on top of the page

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Please add more, if I missed something!

### CODE REVIEW

**Comment by DavertMik** [comment]
Actually, I placed feature list in a sidebar. See the `sidebar` section in a Yaml in a top of a file. 
I think features should be kept there but If you think they are not as visible as they should be I'd probably update the layout

**Comment by ThomasLandauer** [comment]
You mean the list starting with `* Combine **all testing levels** (acceptance, functional, unit)`?  
These are general Codeception advantages (not features). I'm talking about specific features *of the Symfony Module*. This is the first question people are having: "What is it?" The rest ("How can I get it?", "How does it work?") comes later...

**Comment by DavertMik** [comment]
Ok, let's do it this way :)

**Comment by ThomasLandauer** [comment]
Well, I think it would be better to keep the sidebar as you had it. And enter my feature list on top of the regular page, above "Install". Reason: Sidebars are good for additional information, but this is core information (i.e. "What is this all about?")

**Pull request merged**
