### PR TITLE
Document missing @example annotation

### PR DESCRIPTION
**Pull request by oconnedk**
Since [`@testWith`](https://github.com/Codeception/Codeception/issues/6575) is not supported as of `5.0`, document the `@example` codeception annotation (note: annotation, not the attribute, which is already documented).

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by Naktibalda** [comment]
It seems that annotations had been thoroughly replaced with attributes, here is what we had in this exact spot on this page:
```

## Example Annotation

What if you want to execute the same test scenario with different data? In this case you can inject examples
as `\Codeception\Example` instances.
Data is defined via the `@example` annotation, using JSON or Doctrine-style notation (limited to a single line). Doctrine-style:

{% highlight php %}

<?php
class EndpointCest
{
 /**
  * @example ["/api/", 200]
  * @example ["/api/protected", 401]
  * @example ["/api/not-found-url", 404]
  * @example ["/api/faulty", 500]
  */
  public function checkEndpoints(ApiTester $I, \Codeception\Example $example)
  {
    $I->sendGet($example[0]);
    $I->seeResponseCodeIs($example[1]);
  }
}

{% endhighlight %}

JSON:

{% highlight php %}

<?php
class PageCest
{
 /**
  * @example { "url": "/", "title": "Welcome" }
  * @example { "url": "/info", "title": "Info" }
  * @example { "url": "/about", "title": "About Us" }
  * @example { "url": "/contact", "title": "Contact Us" }
  */
  public function staticPages(AcceptanceTester $I, \Codeception\Example $example)
  {
    $I->amOnPage($example['url']);
    $I->see($example['title'], 'h1');
    $I->seeInTitle($example['title']);
  }
}

{% endhighlight %}

<div class="alert alert-info">
If you use JSON notation please keep in mind that all string keys
and values should be enclosed in double quotes (`"`) according to JSON standard.
</div>

Key-value data in Doctrine-style annotation syntax:

{% highlight php %}

<?php
class PageCest
{
 /**
  * @example(url="/", title="Welcome")
  * @example(url="/info", title="Info")
  * @example(url="/about", title="About Us")
  * @example(url="/contact", title="Contact Us")
  */
  public function staticPages(AcceptanceTester $I, \Codeception\Example $example)
  {
    $I->amOnPage($example['url']);
    $I->see($example['title'], 'h1');
    $I->seeInTitle($example['title']);
  }
}

{% endhighlight %}
```
https://raw.githubusercontent.com/Codeception/codeception.github.com/3597943bd0bee905e4b1cb099b7bd7345c9d5afb/docs/07-AdvancedUsage.md

**Comment by oconnedk** [comment]
Thanks @Naktibalda , but I think the "attribute" approach only works for `Cest` tests, which is why I mention this approach [for `Unit` tests](https://github.com/Codeception/codeception.github.com/pull/662/files).
I tried the "attribute" approach with a `Unit` test and it did nothing, so I think it's worth documenting the `@example` annotation approach.

**Comment by Naktibalda** [comment]
This file is autogenerated now, the source document is https://github.com/Codeception/codeception.github.com/blob/master/guides/07-AdvancedUsage.md

**Comment by oconnedk** [comment]
> This file is autogenerated now, the source document is https://github.com/Codeception/codeception.github.com/blob/master/guides/07-AdvancedUsage.md

OK, sure. I think this should work:
https://github.com/Codeception/codeception.github.com/pull/662/files

**Pull request merged**
