### PR TITLE
Update 03-AcceptanceTests.md

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Switching to new name for facebook web-driver

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
Thanks but this fix sould go into main repo Codeception/Codeception into docs folder

**Comment by ThomasLandauer** [comment]
@DavertMik Ehm, there is no "docs" folder at https://github.com/Codeception/Codeception And you merged https://github.com/Codeception/codeception.github.com/pull/353 into this repo too...

**Comment by ThomasLandauer** [comment]
Ping @DavertMik, @Naktibalda  please reopen this and https://github.com/Codeception/codeception.github.com/pull/367 too

**Comment by Naktibalda** [comment]
This pull request can't be reopenned, because your fork has been deleted.

**Comment by ThomasLandauer** [comment]
Did I delete it? Well, probably cause GitHub told me to do so... ;-)

**Pull request closed without merging**
