### PR TITLE
Refine UX for new and current users.

### PR DESCRIPTION
**Pull request by cjaoude**
Optimize onboarding new users
+ single CTA
+ new Quick Start guide (wip)

Optimize main nav for current users
+ clean nav focused on developer docs
+ pair Quick Start with logo (looks cool, stands out, a fast click)

Minor fixes to footer, css, spacing

TODO:
hero needs to be re-done due to conflict with navbar in responsive mode , but requires removing ‘container’ from around {{ content }} in bootstrap.html (which means changing all the pages)

### CODE REVIEW

**Comment by cjaoude** [comment]
I've only been using it a day ...but for the record I hate Jekyll, slow as #$@!
:)

**Comment by DavertMik** [comment]
Personally I rarely use it, instead I push everything to GH :)
Maybe you use old ruby, so it's slow? Ruby 2.2 should be used at least
but anyway, I agree Jekyll is slow (

**Comment by DavertMik** [comment]
Thanks, I really like menu optimizations. Please proceed

> but requires removing ‘container’ from around {{ content }} in bootstrap.html (which means changing all the pages)

yep

**Comment by DavertMik** [comment]
Ups https://twitter.com/miron84/status/710477808166965249

**Comment by cjaoude** [comment]
i'll have a look, didn't touch anything with the sidenav... :/

**Pull request merged**
